version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mysql_container:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql

  phpmyadmin_container:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_container
    ports:
      - "2022:80"

  redis_container:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes --requirepass $RADIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres_data_container:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  mongodb_data_container:
  mysql_data_container:
  redis_data_container:
  postgres_data_container:
  pgadmin_data_container:
